### ISSUE TITLE
抓取音乐可能遇到的问题

### ISSUE THREAD

**Issue by rubby33** [scienceswork/music-webcollector#1]
你好，请问下：
我尝试直接使用这个项目去抓取网易云音乐的音乐列表。

是否还需要解决一些问题，抓取这么多的网页内容，是否容易导致封ip地址等？
我跑了一会儿，就发现readtime out了，能否加一些机制避免这些？？
还有哪些需要注意的啊？谢谢啊！

**Comment by scienceswork** [comment]
之前采集了几千万条都没有问题，音乐版权越来越严重的情况下，频繁采集肯定会封锁ip的，建议可以使用ip代理来采集，这个框架已经封装了ip代理，很容易就会可以实现了。timeout一般都是服务器对请求的限制，还有一个问题就是不建议写入csv，因为是当教程用，所以选择了最简单的写入csv，建议写入数据库，如果要完善的话，引入redis，可以查看下文档，默认是直接使用内存去重的（内存不够时将URL映射到硬盘），使用redis，就可以做很多好玩的东西了。建议读一下这个框架的文档。
